{% set name = "pyinaturalist-convert" %}
{% set python_min = "3.10" %}
{% set version = "0.7.1" %}
{% set hash_val = "40262f510a611786543f0e4597005c0a516ccb52c9ca562be9e325725875ffc2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - flatten-dict >=0.4
    - gpxpy >=1.4.2
    - openpyxl >=2.6
    - pandas >=1.2
    - pyarrow >=11.0
    - pyinaturalist >=0.20.1
    - pytables >=3.6
    - requests-cache >=1.2
    - sqlalchemy >=2.0
    - tablib >=3.0
    - tabulate >=0.8
    - xmltodict >=0.12

test:
  imports:
    - pyinaturalist_convert
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyinat/pyinaturalist-convert
  summary: Convert iNaturalist observation data to and from multiple formats
  license: MIT
  license_file: LICENSE
  doc_url: https://pyinaturalist.readthedocs.io
  dev_url: https://github.com/pyinat/pyinaturalist-convert


extra:
  recipe-maintainers:
    - jwcook
